id: A3B8B4A80
title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:42.111519
  last_modified_at: 2022-03-01 00:58:42.111527
